version: '3.8'

services:
  backend:
    build:
      context: ./backend_files
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    networks:
      - superkart_network
    restart: always

  frontend:
    build:
      context: ./frontend_files
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:7860  # 'backend' is the service name in docker-compose
    networks:
      - superkart_network
    restart: always

networks:
  superkart_network:
    driver: bridge
